name: locally_flutter_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  path_provider: ^1.6.22
  get: ^3.13.2
  google_fonts: ^1.1.0
  device_preview: ^0.4.8
  carousel_slider: ^2.3.1
  flutter_vector_icons: ^0.2.1
  flare_loading: ^2.1.1
  supercharged: ^1.10.0
  firebase_core: "0.5.0+1"
  cloud_firestore: "^0.14.1+3"
  firebase_auth: "^0.18.1+2"
  firebase_storage: "^5.0.0-dev.3"
  flare_flutter: ^2.0.6
  qr_flutter: ^3.2.0
  get_it: ^5.0.1
  shared_preferences: ^0.5.12+2
  flutter_sequence_animation: "^3.0.0"
  flutter_circle_color_picker: ^0.2.0
  image_picker: ^0.6.7+12
  flutter_svg: ^0.19.1
  uuid: ^2.2.2
  qr_code_scanner: ^0.0.13
  cached_network_image: ^2.3.3
  google_sign_in: "^4.5.1"
  animations: ^1.1.2
  delayed_display: ^1.0.3
  sa_stateless_animation: ^1.0.3
  lottie: ^0.7.0+1
  animate_do: ^1.7.3
  flutter_slidable: ^0.5.7
  onesignal_flutter: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - assets/logos/
    - assets/animations/
    - assets/png/
    - assets/gif/
    - assets/svg/